builds:
  - binary: cast
    main: ./cmd/cast
    ldflags: -s -w -X=github.com/barnybug/go-cast.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm
    ignore:
      - goos: darwin
        goarch: 386
    hooks:
      post: make upx

archives:
- name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format: binary
  replacements:
    darwin: mac
